//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ebEntities : DbContext
    {
        public ebEntities()
            : base("name=ebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisDailyOrder> AnalysisDailyOrder { get; set; }
        public virtual DbSet<AnalysisDailyProduct> AnalysisDailyProduct { get; set; }
        public virtual DbSet<AnalysisEmployeeOrder> AnalysisEmployeeOrder { get; set; }
        public virtual DbSet<ApprovalInfo> ApprovalInfo { get; set; }
        public virtual DbSet<ApprovalRecord> ApprovalRecord { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BSArea> BSArea { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Deliverys> Deliverys { get; set; }
        public virtual DbSet<DeliverysDocument> DeliverysDocument { get; set; }
        public virtual DbSet<ECommercePlatform> ECommercePlatform { get; set; }
        public virtual DbSet<ECommercePushInventoryRecord> ECommercePushInventoryRecord { get; set; }
        public virtual DbSet<ECommercePushPriceRecord> ECommercePushPriceRecord { get; set; }
        public virtual DbSet<ECommercePushRecord> ECommercePushRecord { get; set; }
        public virtual DbSet<ExpressCompany> ExpressCompany { get; set; }
        public virtual DbSet<FTPInfo> FTPInfo { get; set; }
        public virtual DbSet<InventoryWarnSend> InventoryWarnSend { get; set; }
        public virtual DbSet<LanguagePack> LanguagePack { get; set; }
        public virtual DbSet<Mall> Mall { get; set; }
        public virtual DbSet<MallDetail> MallDetail { get; set; }
        public virtual DbSet<MallProduct> MallProduct { get; set; }
        public virtual DbSet<MallProductPriceRange> MallProductPriceRange { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderBilling> OrderBilling { get; set; }
        public virtual DbSet<OrderCancel> OrderCancel { get; set; }
        public virtual DbSet<OrderChangeRecord> OrderChangeRecord { get; set; }
        public virtual DbSet<OrderClaimCache> OrderClaimCache { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<OrderDetailAdjustment> OrderDetailAdjustment { get; set; }
        public virtual DbSet<OrderExchange> OrderExchange { get; set; }
        public virtual DbSet<OrderGift> OrderGift { get; set; }
        public virtual DbSet<OrderLog> OrderLog { get; set; }
        public virtual DbSet<OrderModify> OrderModify { get; set; }
        public virtual DbSet<OrderPayment> OrderPayment { get; set; }
        public virtual DbSet<OrderPaymentDetail> OrderPaymentDetail { get; set; }
        public virtual DbSet<OrderPaymentGift> OrderPaymentGift { get; set; }
        public virtual DbSet<OrderReceive> OrderReceive { get; set; }
        public virtual DbSet<OrderReject> OrderReject { get; set; }
        public virtual DbSet<OrderReturn> OrderReturn { get; set; }
        public virtual DbSet<OrderReturnDeliverysDocument> OrderReturnDeliverysDocument { get; set; }
        public virtual DbSet<OrderShippingAdjustment> OrderShippingAdjustment { get; set; }
        public virtual DbSet<OrderValueAddedService> OrderValueAddedService { get; set; }
        public virtual DbSet<OrderWMSReply> OrderWMSReply { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductSet> ProductSet { get; set; }
        public virtual DbSet<ProductSetDetail> ProductSetDetail { get; set; }
        public virtual DbSet<ProductSetMall> ProductSetMall { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<PromotionGift> PromotionGift { get; set; }
        public virtual DbSet<PromotionMall> PromotionMall { get; set; }
        public virtual DbSet<PromotionProduct> PromotionProduct { get; set; }
        public virtual DbSet<PromotionProductInventory> PromotionProductInventory { get; set; }
        public virtual DbSet<SapUploadLog> SapUploadLog { get; set; }
        public virtual DbSet<SapUploadLogDetail> SapUploadLogDetail { get; set; }
        public virtual DbSet<SapUploadLogWait> SapUploadLogWait { get; set; }
        public virtual DbSet<SendMailGroup> SendMailGroup { get; set; }
        public virtual DbSet<ServiceModuleInfo> ServiceModuleInfo { get; set; }
        public virtual DbSet<ServiceModuleJob> ServiceModuleJob { get; set; }
        public virtual DbSet<SMMailSend> SMMailSend { get; set; }
        public virtual DbSet<SMMailSended> SMMailSended { get; set; }
        public virtual DbSet<SMSSend> SMSSend { get; set; }
        public virtual DbSet<SMSSended> SMSSended { get; set; }
        public virtual DbSet<StorageInfo> StorageInfo { get; set; }
        public virtual DbSet<SysConfig> SysConfig { get; set; }
        public virtual DbSet<SysFunction> SysFunction { get; set; }
        public virtual DbSet<SysFunctionGroup> SysFunctionGroup { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleFunction> SysRoleFunction { get; set; }
        public virtual DbSet<SysUploadModel> SysUploadModel { get; set; }
        public virtual DbSet<UserEmployee> UserEmployee { get; set; }
        public virtual DbSet<UserEmployeeGroup> UserEmployeeGroup { get; set; }
        public virtual DbSet<UserEmployeeLevel> UserEmployeeLevel { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserMalls> UserMalls { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<WarehouseInfo> WarehouseInfo { get; set; }
        public virtual DbSet<WebApiAccount> WebApiAccount { get; set; }
        public virtual DbSet<WebApiRoles> WebApiRoles { get; set; }
        public virtual DbSet<View_ApprovalRecord> View_ApprovalRecord { get; set; }
        public virtual DbSet<View_DeliverysNote> View_DeliverysNote { get; set; }
        public virtual DbSet<View_Mall_Platform> View_Mall_Platform { get; set; }
        public virtual DbSet<View_MallDetail> View_MallDetail { get; set; }
        public virtual DbSet<View_MallProductInventory> View_MallProductInventory { get; set; }
        public virtual DbSet<View_OrderCancel> View_OrderCancel { get; set; }
        public virtual DbSet<View_OrderDetail> View_OrderDetail { get; set; }
        public virtual DbSet<View_OrderDetail_Deliverys> View_OrderDetail_Deliverys { get; set; }
        public virtual DbSet<View_OrderDetail_Receive> View_OrderDetail_Receive { get; set; }
        public virtual DbSet<View_OrderExchange> View_OrderExchange { get; set; }
        public virtual DbSet<View_OrderModify> View_OrderModify { get; set; }
        public virtual DbSet<View_OrderReject> View_OrderReject { get; set; }
        public virtual DbSet<View_OrderReturn> View_OrderReturn { get; set; }
        public virtual DbSet<View_ProductSet> View_ProductSet { get; set; }
        public virtual DbSet<View_Promotion> View_Promotion { get; set; }
        public virtual DbSet<View_SysFunction> View_SysFunction { get; set; }
        public virtual DbSet<View_UserEmployee> View_UserEmployee { get; set; }
    }
}
