//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRecord
    {
        public long ID { get; set; }
        public int ApprovalProjectID { get; set; }
        public string ApprovalIdentify { get; set; }
        public string ApprovalTableName { get; set; }
        public long DetailID { get; set; }
        public int ApprovalUserId { get; set; }
        public string ApprovalRemark { get; set; }
        public System.DateTime ApprovalDate { get; set; }
    }
}
