//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ID { get; set; }
        public string CustomerNo { get; set; }
        public string PlatformUserNo { get; set; }
        public string PlatformUserName { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Addr { get; set; }
        public string Zipcode { get; set; }
        public string CountryCode { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Town { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
