//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverys
    {
        public long Id { get; set; }
        public string MallSapCode { get; set; }
        public string OrderNo { get; set; }
        public string SubOrderNo { get; set; }
        public int ExpressId { get; set; }
        public string ExpressName { get; set; }
        public string InvoiceNo { get; set; }
        public int Packages { get; set; }
        public string ExpressType { get; set; }
        public decimal ExpressAmount { get; set; }
        public string Warehouse { get; set; }
        public string ReceiveTime { get; set; }
        public string ClearUpTime { get; set; }
        public string DeliveryDate { get; set; }
        public int ExpressStatus { get; set; }
        public string ExpressMsg { get; set; }
        public string Remark { get; set; }
        public string DeliveryChangeUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsNeedPush { get; set; }
    }
}
