//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECommercePlatform
    {
        public int Id { get; set; }
        public int PlatformCode { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string AppKey { get; set; }
        public string AppSecret { get; set; }
        public string ServicePowers { get; set; }
        public bool IsUsed { get; set; }
    }
}
