//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressCompany
    {
        public int Id { get; set; }
        public string ExpressName { get; set; }
        public string Code { get; set; }
        public string ExpressUrl { get; set; }
        public string APIUrl { get; set; }
        public string APIClientID { get; set; }
        public string AppClientSecret { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> AccessTokenExpires { get; set; }
        public int SortID { get; set; }
        public bool IsUsed { get; set; }
    }
}
