//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalInterfaceLog
    {
        public long Id { get; set; }
        public int LogType { get; set; }
        public string ValidMessage { get; set; }
        public string IP { get; set; }
        public string ReceiveMessage { get; set; }
        public bool ReturnResult { get; set; }
        public string ReturnMessage { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
