//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguagePack
    {
        public long ID { get; set; }
        public int FunctionID { get; set; }
        public string PackKey { get; set; }
        public string PackChinese { get; set; }
        public string PackEnglish { get; set; }
        public string PackTraditionalChinese { get; set; }
        public string PackKorean { get; set; }
        public string PackThai { get; set; }
        public string PackJapan { get; set; }
        public int SeqNumber { get; set; }
        public bool IsDelete { get; set; }
    }
}
