//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallDetail
    {
        public int MallId { get; set; }
        public string MallName { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string ContactReceiver { get; set; }
        public string ContactPhone { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string StoreType { get; set; }
        public string RelatedBrandStore { get; set; }
        public string Remark { get; set; }
    }
}
