//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallProduct
    {
        public long ID { get; set; }
        public string MallSapCode { get; set; }
        public string MallProductTitle { get; set; }
        public string MallProductPic { get; set; }
        public string MallProductId { get; set; }
        public string MallSkuId { get; set; }
        public string MallSkuPropertiesName { get; set; }
        public int ProductType { get; set; }
        public string SKU { get; set; }
        public string SkuGrade { get; set; }
        public decimal Price { get; set; }
        public decimal SalesPrice { get; set; }
        public string SalesValidBegin { get; set; }
        public string SalesValidEnd { get; set; }
        public int Quantity { get; set; }
        public System.DateTime QuantityEditDate { get; set; }
        public bool IsOnSale { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime EditDate { get; set; }
    }
}
