//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderShippingAdjustment
    {
        public long Id { get; set; }
        public string OrderNo { get; set; }
        public string ShipmentId { get; set; }
        public decimal NetPrice { get; set; }
        public decimal Tax { get; set; }
        public decimal GrossPrice { get; set; }
        public decimal BasePrice { get; set; }
        public decimal TaxBasis { get; set; }
        public decimal AdjustmentNetPrice { get; set; }
        public decimal AdjustmentTax { get; set; }
        public decimal AdjustmentGrossPrice { get; set; }
        public decimal AdjustmentBasePrice { get; set; }
        public decimal AdjustmentTaxBasis { get; set; }
        public string AdjustmentLineitemText { get; set; }
        public string AdjustmentPromotionId { get; set; }
        public string AdjustmentCampaignId { get; set; }
    }
}
