//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderModify
    {
        public long Id { get; set; }
        public string MallSapCode { get; set; }
        public string OrderNo { get; set; }
        public string SubOrderNo { get; set; }
        public string CustomerName { get; set; }
        public string CountryCode { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Addr { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Zipcode { get; set; }
        public int ExpressId { get; set; }
        public string InvoiceNo { get; set; }
        public int UserId { get; set; }
        public System.DateTime AddDate { get; set; }
        public int AcceptUserId { get; set; }
        public Nullable<System.DateTime> AcceptUserDate { get; set; }
        public string AcceptRemark { get; set; }
        public string Remark { get; set; }
        public bool FromApi { get; set; }
        public bool IsSystemModify { get; set; }
        public int Status { get; set; }
        public int ManualUserId { get; set; }
        public string ManualRemark { get; set; }
        public Nullable<System.DateTime> ManualUserDate { get; set; }
    }
}
