//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChangeRecord
    {
        public long Id { get; set; }
        public string OrderNo { get; set; }
        public string SubOrderNo { get; set; }
        public int Type { get; set; }
        public string DetailTableName { get; set; }
        public long DetailId { get; set; }
        public int UserId { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
        public bool ApiIsRead { get; set; }
        public Nullable<System.DateTime> ApiReadDate { get; set; }
        public Nullable<System.DateTime> ApiReplyDate { get; set; }
        public string ApiReplyMsg { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
