//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReject
    {
        public long Id { get; set; }
        public string MallSapCode { get; set; }
        public string OrderNo { get; set; }
        public int UserId { get; set; }
        public int Reason { get; set; }
        public string Remark { get; set; }
        public int AcceptUserId { get; set; }
        public Nullable<System.DateTime> AcceptUserDate { get; set; }
        public string AcceptRemark { get; set; }
        public bool FromApi { get; set; }
        public string SubOrderNo { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
        public string RequestId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsSystemReject { get; set; }
    }
}
