//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderExchange
    {
        public long Id { get; set; }
        public string MallSapCode { get; set; }
        public string OrderNo { get; set; }
        public int UserId { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Reason { get; set; }
        public string Remark { get; set; }
        public string SubOrderNo { get; set; }
        public string NewSKU { get; set; }
        public int Quantity { get; set; }
        public decimal DifferenceAmount { get; set; }
        public decimal ExpressAmount { get; set; }
        public bool FromApi { get; set; }
        public int Status { get; set; }
        public string ShippingCompany { get; set; }
        public string ShippingNo { get; set; }
        public string RequestId { get; set; }
        public string CustomerName { get; set; }
        public string Addr { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Zipcode { get; set; }
        public int AcceptUserId { get; set; }
        public Nullable<System.DateTime> AcceptUserDate { get; set; }
        public string AcceptRemark { get; set; }
        public int SendUserId { get; set; }
        public Nullable<System.DateTime> SendUserDate { get; set; }
        public string SendRemark { get; set; }
        public int ManualUserId { get; set; }
        public string ManualRemark { get; set; }
        public Nullable<System.DateTime> ManualUserDate { get; set; }
    }
}
