//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public long Id { get; set; }
        public string PromotionName { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int RuleType { get; set; }
        public int ProductQuantity { get; set; }
        public int GiftQuantity { get; set; }
        public decimal TotalAmount { get; set; }
        public int GiftRule { get; set; }
        public int GiftType { get; set; }
        public int GiftMaxQuantity { get; set; }
        public int GiftCurrentQuantity { get; set; }
        public int UserId { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsApproval { get; set; }
        public bool IsDelete { get; set; }
    }
}
