//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SapUploadLogDetail
    {
        public int Id { get; set; }
        public int LogId { get; set; }
        public string OrderNo { get; set; }
        public string SubOrderNo { get; set; }
        public string UploadNo { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> SapCreationDate { get; set; }
        public Nullable<System.DateTime> SapProcessTimeStamp { get; set; }
        public int LogType { get; set; }
        public int Status { get; set; }
        public string MallStoreCode { get; set; }
        public string SAPDNNumber { get; set; }
        public bool IsAppendShippment { get; set; }
        public bool IsAppendSurcharge { get; set; }
    }
}
