//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SapUploadLog
    {
        public int Id { get; set; }
        public Nullable<int> LogType { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public int TotalCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MallSapCode { get; set; }
        public string TransactionDate { get; set; }
    }
}
