//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceModuleJob
    {
        public long ID { get; set; }
        public int ModuleID { get; set; }
        public int OperType { get; set; }
        public int Status { get; set; }
        public string StatusMessage { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
