//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceModuleInfo
    {
        public int ModuleID { get; set; }
        public string ModuleMark { get; set; }
        public string ModuleTitle { get; set; }
        public string ModuleWorkflowID { get; set; }
        public string ModuleAssembly { get; set; }
        public string ModuleType { get; set; }
        public string ModuleBLL { get; set; }
        public string Remark { get; set; }
        public bool IsRun { get; set; }
        public bool IsNotify { get; set; }
        public int FixType { get; set; }
        public string FixTime { get; set; }
        public int SortID { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> NextRunTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
