//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMailSended
    {
        public long ID { get; set; }
        public string MailTitle { get; set; }
        public string MailContent { get; set; }
        public int SendUserid { get; set; }
        public string SendUserIP { get; set; }
        public int SendState { get; set; }
        public string RecvMail { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime SendTime { get; set; }
    }
}
