//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSend
    {
        public long ID { get; set; }
        public string RecvMobile { get; set; }
        public string Sender { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public int SendUserid { get; set; }
        public string SendUserIP { get; set; }
        public int SendState { get; set; }
        public int SendCount { get; set; }
        public string SendMessage { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
