//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageInfo
    {
        public int StorageID { get; set; }
        public string CompanyCode { get; set; }
        public string PlantName { get; set; }
        public string PlantCode { get; set; }
        public string StorageName { get; set; }
        public string StorageCode { get; set; }
        public string VirtualSAPCode { get; set; }
        public bool IsMain { get; set; }
        public string Remark { get; set; }
        public int SortID { get; set; }
        public bool IsLock { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
