//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRole
    {
        public int Roleid { get; set; }
        public string RoleName { get; set; }
        public string RoleMemo { get; set; }
        public int SeqNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
