//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUploadModel
    {
        public int ID { get; set; }
        public string UploadName { get; set; }
        public string ModelMark { get; set; }
        public int FileType { get; set; }
        public int MaxFileSize { get; set; }
        public int MaxFileCount { get; set; }
        public string AllowFile { get; set; }
        public string SaveCatalog { get; set; }
        public string SaveStyle { get; set; }
        public bool IsRename { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
