//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MallProductInventory
    {
        public long ID { get; set; }
        public string MallSapCode { get; set; }
        public string MallProductId { get; set; }
        public int ProductType { get; set; }
        public string SKU { get; set; }
        public string SkuGrade { get; set; }
        public decimal Price { get; set; }
        public decimal SalesPrice { get; set; }
        public int Quantity { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime EditDate { get; set; }
        public string MallProductTitle { get; set; }
        public string MallProductPic { get; set; }
        public string MallSkuId { get; set; }
        public string MallSkuPropertiesName { get; set; }
        public bool IsOnSale { get; set; }
        public string GroupDesc { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MatlGroup { get; set; }
        public string Material { get; set; }
        public string GdVal { get; set; }
        public string EAN { get; set; }
        public decimal SupplyPrice { get; set; }
        public decimal MarketPrice { get; set; }
        public string ProductName { get; set; }
        public bool IsCommon { get; set; }
        public bool IsSet { get; set; }
        public bool IsGift { get; set; }
        public string ProductId { get; set; }
        public long PID { get; set; }
        public int TotalQuantity { get; set; }
        public System.DateTime QuantityEditDate { get; set; }
        public string MallName { get; set; }
        public decimal ProductVolume { get; set; }
        public decimal ProductLength { get; set; }
        public decimal ProductWidth { get; set; }
        public decimal ProductHeight { get; set; }
        public decimal ProductWeight { get; set; }
        public string SalesValidBegin { get; set; }
        public string SalesValidEnd { get; set; }
    }
}
