//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductSet
    {
        public long Id { get; set; }
        public string SetName { get; set; }
        public string SetCode { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Inventory { get; set; }
        public string Remark { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsApproval { get; set; }
        public bool IsDelete { get; set; }
        public string AddUserName { get; set; }
    }
}
