//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderDetail
    {
        public string MallSapCode { get; set; }
        public string MallName { get; set; }
        public string OrderNo { get; set; }
        public int PaymentType { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal BalanceAmount { get; set; }
        public decimal PointAmount { get; set; }
        public int Point { get; set; }
        public decimal DeliveryFee { get; set; }
        public int OrderType { get; set; }
        public int OrderSource { get; set; }
        public int PlatformType { get; set; }
        public int Status { get; set; }
        public string EBStatus { get; set; }
        public decimal AdjustAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string Remark { get; set; }
        public string CustomerNo { get; set; }
        public string SubOrderNo { get; set; }
        public string MallProductId { get; set; }
        public string MallSkuId { get; set; }
        public string ProductName { get; set; }
        public string ProductId { get; set; }
        public string SKU { get; set; }
        public int Quantity { get; set; }
        public decimal SupplyPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal ProductPaymentAmount { get; set; }
        public decimal ActualPaymentAmount { get; set; }
        public int ProductStatus { get; set; }
        public int ShippingStatus { get; set; }
        public int CancelQuantity { get; set; }
        public int ReturnQuantity { get; set; }
        public int ExchangeQuantity { get; set; }
        public int RejectQuantity { get; set; }
        public bool IsReservation { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public bool IsSet { get; set; }
        public bool IsError { get; set; }
        public bool IsSystemCancel { get; set; }
        public System.DateTime SubAddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string ErrorMsg { get; set; }
        public bool IsDelete { get; set; }
        public bool IsExchangeNew { get; set; }
        public decimal TaxRate { get; set; }
        public decimal Tax { get; set; }
        public long OrderId { get; set; }
        public string SkuGrade { get; set; }
        public bool IsSetOrigin { get; set; }
        public string ReservationRemark { get; set; }
        public string ErrorRemark { get; set; }
        public long Id { get; set; }
        public long DetailID { get; set; }
        public string ProductPic { get; set; }
        public string SkuProperties { get; set; }
        public string ProductEBStatus { get; set; }
        public string SetCode { get; set; }
        public string TaxNumber { get; set; }
        public string InvoiceMessage { get; set; }
        public string OffLineSapCode { get; set; }
        public bool IsGift { get; set; }
        public string ESTArrivalTime { get; set; }
        public int CreateSource { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public bool IsPre { get; set; }
        public bool IsUrgent { get; set; }
        public long PlatformOrderId { get; set; }
        public string ExtraRequest { get; set; }
        public int ShippingType { get; set; }
        public bool IsEmployee { get; set; }
        public string PaymentAttribute { get; set; }
        public string ParentSubOrderNo { get; set; }
        public int ShippingMethod { get; set; }
        public decimal RRPPrice { get; set; }
        public string LoyaltyCardNo { get; set; }
        public bool IsStop { get; set; }
        public string ShippingProvider { get; set; }
        public string DeliveringPlant { get; set; }
        public string PackageNumber { get; set; }
    }
}
