//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderDetail_Deliverys
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string OrderNo { get; set; }
        public string SubOrderNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string MallProductId { get; set; }
        public string MallSkuId { get; set; }
        public string ProductName { get; set; }
        public string ProductPic { get; set; }
        public string ProductId { get; set; }
        public string SetCode { get; set; }
        public string SKU { get; set; }
        public string SkuProperties { get; set; }
        public int Quantity { get; set; }
        public decimal SupplyPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal ActualPaymentAmount { get; set; }
        public int Status { get; set; }
        public string EBStatus { get; set; }
        public int ShippingStatus { get; set; }
        public int CancelQuantity { get; set; }
        public int ReturnQuantity { get; set; }
        public int ExchangeQuantity { get; set; }
        public decimal Tax { get; set; }
        public bool IsReservation { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string ReservationRemark { get; set; }
        public bool IsSet { get; set; }
        public bool IsSetOrigin { get; set; }
        public bool IsPre { get; set; }
        public bool IsExchangeNew { get; set; }
        public bool IsSystemCancel { get; set; }
        public decimal TaxRate { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public bool IsError { get; set; }
        public string ErrorMsg { get; set; }
        public string ErrorRemark { get; set; }
        public bool IsDelete { get; set; }
        public long DeliveryID { get; set; }
        public string MallSapCode { get; set; }
        public int ExpressId { get; set; }
        public string ExpressName { get; set; }
        public string InvoiceNo { get; set; }
        public int Packages { get; set; }
        public string ExpressType { get; set; }
        public decimal ExpressAmount { get; set; }
        public string Warehouse { get; set; }
        public string ReceiveTime { get; set; }
        public string ClearUpTime { get; set; }
        public string DeliveryDate { get; set; }
        public int ExpressStatus { get; set; }
        public string ExpressMsg { get; set; }
        public string Remark { get; set; }
        public System.DateTime DeliverysDate { get; set; }
        public bool IsNeedPush { get; set; }
        public int RejectQuantity { get; set; }
        public int ShippingType { get; set; }
        public string ParentSubOrderNo { get; set; }
        public bool IsUrgent { get; set; }
        public bool IsEmployee { get; set; }
        public decimal RRPPrice { get; set; }
        public string ShippingProvider { get; set; }
        public string DeliveringPlant { get; set; }
        public string DeliveryChangeUrl { get; set; }
    }
}
