//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderCancel
    {
        public long Id { get; set; }
        public string OrderNo { get; set; }
        public string MallSapCode { get; set; }
        public string MallName { get; set; }
        public int UserId { get; set; }
        public string AddUserName { get; set; }
        public string Remark { get; set; }
        public bool FromApi { get; set; }
        public string SubOrderNo { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
        public int RefundUserId { get; set; }
        public int AcceptUserId { get; set; }
        public Nullable<System.DateTime> AcceptUserDate { get; set; }
        public string AcceptRemark { get; set; }
        public string AcceptUserName { get; set; }
        public string RefundUserName { get; set; }
        public string ManualUserName { get; set; }
        public bool IsFromCOD { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal RefundPoint { get; set; }
        public Nullable<System.DateTime> RefundUserDate { get; set; }
        public string RefundRemark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public int ManualUserId { get; set; }
        public string ManualRemark { get; set; }
        public Nullable<System.DateTime> ManualUserDate { get; set; }
        public bool IsSystemCancel { get; set; }
        public long ChangeID { get; set; }
        public int Type { get; set; }
        public int ApiStatus { get; set; }
        public bool ApiIsRead { get; set; }
        public Nullable<System.DateTime> ApiReadDate { get; set; }
        public Nullable<System.DateTime> ApiReplyDate { get; set; }
        public string ApiReplyMsg { get; set; }
        public bool IsDelete { get; set; }
        public int Reason { get; set; }
        public string RequestId { get; set; }
        public decimal RefundExpress { get; set; }
    }
}
