//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MallDetail
    {
        public int Id { get; set; }
        public int PlatformCode { get; set; }
        public string SapCode { get; set; }
        public int MallType { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public int InterfaceType { get; set; }
        public string UserID { get; set; }
        public string Token { get; set; }
        public string TokenTime { get; set; }
        public string RefreshToken { get; set; }
        public int FtpID { get; set; }
        public int SortID { get; set; }
        public string VirtualWMSCode { get; set; }
        public string Remark { get; set; }
        public bool IsUsed { get; set; }
        public bool IsOpenService { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> MallId { get; set; }
        public string MallName { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string ContactReceiver { get; set; }
        public string ContactPhone { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string StoreType { get; set; }
        public string RelatedBrandStore { get; set; }
    }
}
