//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SysFunction
    {
        public int Funcid { get; set; }
        public string FuncName { get; set; }
        public int Groupid { get; set; }
        public int SeqNumber { get; set; }
        public short FuncType { get; set; }
        public string FuncSign { get; set; }
        public string FuncUrl { get; set; }
        public string FuncPower { get; set; }
        public string FuncTarget { get; set; }
        public string FuncMemo { get; set; }
        public bool IsShow { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string GroupName { get; set; }
    }
}
