//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseInfo
    {
        public int ID { get; set; }
        public string WarehouseName { get; set; }
        public string CompanyName { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string ContactName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Postcode { get; set; }
        public string Town { get; set; }
        public string Country { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public bool IsDefault { get; set; }
        public string Remark { get; set; }
        public int SortID { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
