//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebApiAccount
    {
        public int Id { get; set; }
        public string AppID { get; set; }
        public string Token { get; set; }
        public string CompanyName { get; set; }
        public string Ips { get; set; }
        public string Remark { get; set; }
        public bool IsUsed { get; set; }
    }
}
