//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebApiLog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Msg { get; set; }
        public string LogLevel { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
