//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAppOperationLog
    {
        public long LogID { get; set; }
        public int OperationType { get; set; }
        public string TableName { get; set; }
        public int UserID { get; set; }
        public string UserIP { get; set; }
        public string RecordID { get; set; }
        public string LogMessage { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
