//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsonite.OMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebApiAccessLog
    {
        public int id { get; set; }
        public int LogType { get; set; }
        public string Url { get; set; }
        public string RequestID { get; set; }
        public string UserID { get; set; }
        public string Ip { get; set; }
        public bool State { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
